name: release-0.10.1

on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string

jobs:
  release-0.10.1:
    runs-on: [self-hosted, release]
    timeout-minutes: 10

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: test
        run: ~/zig-0.10.1/zig build -Drelease-fast=true -Dtarget=x86_64-linux test

      - name: build
        run: ~/zig-0.10.1/zig build -Drelease-fast=true -Dtarget=x86_64-linux

      - name: rename
        run: mv zig-out ${{ inputs.package-name }}

      - name: zip
        run: tar -czf ${{ inputs.package-name }}.tar.gz ${{ inputs.package-name }}

      - name: copy
        run: cp ${{ inputs.package-name }}.tar.gz ~/ci/builds/${{ inputs.package-name }}/${{ inputs.package-name }}.`date '+%s'`.tar.gz
