name: zig-release

on:
  workflow_call:
    inputs:
      zig-version:
        type: string
        required: true
      package-name:
        type: string
        required: true
      zig-build-command:
        type: string
        required: false
        default: "package"
      package-subdir:
        type: string
        required: false
        default: ""
      target:
        type: string
        required: false
        default: "x86_64-linux"
      releaseFlag:
        type: string
        required: false
        default: "-Drelease-fast=true"

jobs:
  zig-release:
    runs-on: [self-hosted, release]
    timeout-minutes: 10

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: test
        run: ~/zig-${{inputs.zig-version}}/zig build ${{inputs.releaseFlag}} -Dtarget=${{inputs.target}} test

      - name: build
        run: ~/zig-${{inputs.zig-version}}/zig build ${{inputs.releaseFlag}} -Dtarget=${{inputs.target}} ${{inputs.zig-build-command}}

      - name: rename
        run: mv zig-out/${{inputs.package-subdir}} ${{inputs.package-name}}

      - name: zip
        run: tar -czf ${{inputs.package-name}}.tar.gz ${{inputs.package-name}}

      - name: copy
        run: mkdir -p ~/ci/builds/${{inputs.package-name}} && cp ${{inputs.package-name}}.tar.gz ~/ci/builds/${{inputs.package-name}}/${{inputs.package-name}}.`date '+%s'`.tar.gz
